project:
  type: website

website:
  title: "Country Populations Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plot-2.qmd
        text: Plot 2
      - about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



